title: "JHON'S PORTFOLIO"
logo: "Midterm Task 1/JPG.jpg"
theme: jekyll-theme-minimal
                                                                                                                                                                                                                               Update _config.yml with new settings.      
